language: python
python:
- 2.7
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script:
  - py.test --cov=./
  - codecov --token=codecov --token=
after_success:
  - bash <(curl -s https://codecov.io/bash)
